# Generated by Django 3.1 on 2020-10-01 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201001_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaning',
            name='meal',
            field=models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('E', 'Evening')], default='M', max_length=1),
        ),
    ]
