# Generated by Django 3.1 on 2020-10-01 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_cleaning_meal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='kind',
        ),
    ]
